// constants/globalStyles.ts
import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  // Sizing
  wFull: { width: "100%" },
  hFull: { height: "100%" },
  w10: { width: 10 },
  w20: { width: 20 },
  w30: { width: 30 },
  w40: { width: 40 },
  h20: { height: 20 },
  h10: { height: 10 },
  h30: { height: 30 },
  h40: { height: 40 },
  w50: { width: 50 },
  h50: { height: 50 },
  h100: { height: 100 },
  w60: { width: 60 },
  h60: { height: 60 },
  w80: { width: 80 },
  h80: { height: 80 },
  w200: { width: 200 },
  h200: { height: 200 },
  w300: { width: 300 },
  h300: { height: 300 },
  w400: { width: 400 },
  h400: { height: 400 },
  w500: { width: 500 },
  h500: { height: 500 },
  w600: { width: 600 },
  h600: { height: 600 },
  wAuto: { width: "auto" },

  // Flex
  flex1: { flex: 1 },
  row: { flexDirection: "row" },
  column: { flexDirection: "column" },
  itemsCenter: { alignItems: "center" },
  justifyCenter: { justifyContent: "center" },
  justifyBetween: { justifyContent: "space-between" },
  center: { alignItems: "center", justifyContent: "center" },
  itemsStart: { alignItems: "flex-start" },
  itemsEnd: { alignItems: "flex-end" },
  justifyStart: { justifyContent: "flex-start" },
  justifyEnd: { justifyContent: "flex-end" },

  // Position
  absolute: { position: "absolute" },
  relative: { position: "relative" },

  // Spacing (extend as needed)
  p2: { padding: 2 },
  pr2: { paddingRight: 2 },
  pl2: { paddingLeft: 2 },
  px2: { paddingHorizontal: 2 },
  py2: { paddingVertical: 2 },
  pt2: { paddingTop: 2 },
  pb2: { paddingBottom: 2 },
  p4: { padding: 4 },
  px4: { paddingHorizontal: 4 },
  py4: { paddingVertical: 4 },
  pr4: { paddingRight: 4 },
  pl4: { paddingLeft: 4 },
  pt4: { paddingTop: 4 },
  pb4: { paddingBottom: 4 },
  p8: { padding: 8 },
  px8: { paddingHorizontal: 8 },
  py8: { paddingVertical: 8 },
  pr8: { paddingRight: 8 },
  pl8: { paddingLeft: 8 },
  pt8: { paddingTop: 8 },
  pb8: { paddingBottom: 8 },
  p12: { padding: 12 },
  px12: { paddingHorizontal: 12 },
  py12: { paddingVertical: 12 },
  pr12: { paddingRight: 12 },
  pl12: { paddingLeft: 12 },
  pt12: { paddingTop: 12 },
  pb12: { paddingBottom: 12 },
  p14: { padding: 14 },
  pr14: { paddingRight: 14 },
  pl14: { paddingLeft: 14 },
  py14: { paddingVertical: 14 },
  px14: { paddingHorizontal: 14 },
  pt14: { paddingTop: 14 },
  pb14: { paddingBottom: 14 },
  p16: { padding: 16 },
  pr16: { paddingRight: 16 },
  pl16: { paddingLeft: 16 },
  py16: { paddingVertical: 16 },
  px16: { paddingHorizontal: 16 },
  pt16: { paddingTop: 16 },
  pb16: { paddingBottom: 16 },
  p20: { padding: 20 },
  px20: { paddingHorizontal: 20 },
  py20: { paddingVertical: 20 },
  pr20: { paddingRight: 20 },
  pl20: { paddingLeft: 20 },
  pt20: { paddingTop: 20 },
  pb20: { paddingBottom: 20 },
  p24: { padding: 24 },
  px24: { paddingHorizontal: 24 },
  py24: { paddingVertical: 24 },
  pr24: { paddingRight: 24 },
  pl24: { paddingLeft: 24 },
  pt24: { paddingTop: 24 },
  pb24: { paddingBottom: 24 },
  m4: { margin: 4 },
  mt4: { marginTop: 4 },
  mt6: { marginTop: 6 },
  mt8: { marginTop: 8 },
  mt12: { marginTop: 12 },
  mt16: { marginTop: 16 },
  mt20: { marginTop: 20 },
  mt24: { marginTop: 24 },
  mb4: { marginBottom: 4 },
  mb6: { marginBottom: 6 },
  mb8: { marginBottom: 8 },
  mb12: { marginBottom: 12 },
  mb16: { marginBottom: 16 },
  mb20: { marginBottom: 20 },
  mb24: { marginBottom: 24 },
  mx4: { marginHorizontal: 4 },
  my4: { marginVertical: 4 },
  mr4: { marginRight: 4 },
  ml4: { marginLeft: 4 },
  m6: { margin: 6 },
  mx6: { marginHorizontal: 6 },
  my6: { marginVertical: 6 },
  mr6: { marginRight: 6 },
  ml6: { marginLeft: 6 },
  m8: { margin: 8 },
  mx8: { marginHorizontal: 8 },
  my8: { marginVertical: 8 },
  mr8: { marginRight: 8 },
  ml8: { marginLeft: 8 },
  m16: { margin: 16 },
  mx16: { marginHorizontal: 16 },
  my16: { marginVertical: 16 },
  mr16: { marginRight: 16 },
  ml16: { marginLeft: 16 },

  // spacing
  spaceY4: { gap: 4 },
  spaceY8: { gap: 8 },
  spaceY12: { gap: 12 },
  spaceY16: { gap: 16 },
  spaceY20: { gap: 20 },
  spaceY24: { gap: 24 },
  spaceX4: { gap: 4 },
  spaceX8: { gap: 8 },
  spaceX12: { gap: 12 },
  spaceX16: { gap: 16 },
  spaceX20: { gap: 20 },
  spaceX24: { gap: 24 },

  // Text
  textCenter: { textAlign: "center" },
  fontBold: { fontWeight: "800" },
  fontSemibold: { fontWeight: "600" },
  fontMedium: { fontWeight: "500" },
  fontLight: { fontWeight: "light" },
  textXl: { fontSize: 24 },
  textLg: { fontSize: 18 },
  textSm: { fontSize: 14 },
  textXs: { fontSize: 12 },
  textXss: { fontSize: 10 },
  textRight: { textAlign: "right" },
  textLeft: { textAlign: "left" },

  // radius
  rounded4: { borderRadius: 4 },
  rounded6: { borderRadius: 6 },
  rounded8: { borderRadius: 8 },
  rounded10: { borderRadius: 10 },
  rounded12: { borderRadius: 12 },
  rounded16: { borderRadius: 16 },
  rounded24: { borderRadius: 24 },
  roundedFull: { borderRadius: "100%" },

  // border
  border1: { borderWidth: 1 },
  border2: { borderWidth: 2 },
  border4: { borderWidth: 4 },
  border6: { borderWidth: 6 },
  border8: { borderWidth: 8 },

  // cases
  capitalize: { textTransform: "capitalize" },
  uppercase: { textTransform: "uppercase" },
  lowercase: { textTransform: "lowercase" },

  overflowHidden: { overflow: "hidden" },

  // gap
  gap2: { gap: 2 },
  gap4: { gap: 4 },
  gap6: { gap: 6 },
  gap8: { gap: 8 },
  gap12: { gap: 12 },
  gap16: { gap: 16 },
  gap20: { gap: 20 },
  gap24: { gap: 24 },

  // shadow
  shadowBlackSM: {
    shadowColor: "#0000005c",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shadowBlackMD: {
    shadowColor: "#0000005c",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shadowBlackLG: {
    shadowColor: "#0000005c",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shadowBlackXL: {
    shadowColor: "#0000005c",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
